version: 2
jobs:
  test_lending_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/lending_model/requirements.txt
            py.test --vv packages/lending_model/tests

workflows:
  version: 2
  test-all:
    jobs:
      - test_lending_model
